import { Meteor } from 'meteor/meteor';
import { createContainer } from 'meteor/react-meteor-data';
import moment from 'moment';
import React from 'react';


import { Catcher } from 'meteor/marvin:imsi-catcher-catcher';

class DetectionsPage extends React.Component {
  handleSimulateDetection() {
    Meteor.call('catcher.simulate-detection', Random.id(), {
      basestationId: "StingWatch Test",
      detectorName: "StingWatch Test",
      message: "This detection is a TEST and was generated by the StingWatch team. These tests help us improve the tool. Thanks for using StingWatch.",
      score: 100,
      longitude: 32.890237,
      latitude: -26.167970
    }, () => {

    })
  }

  renderDetectionGenerator() {
    return (
      <div className='m-y-3 text-xs-center'>
        <h2>Simulate Detection</h2>
        <h3 className='m-y-1'>
          WARNING: This will cause all apps to register a new detection.
          Only use in development.
        </h3>
        <button className='btn btn-danger btn-lg' onClick={this.handleSimulateDetection}>
          Simulate Detection
        </button>
      </div>
    );
  }

  renderDetection(detection) {
    return (
      <tr key={detection._id}>
        <th scope="row">{detection.deviceId}</th>
        <td>{detection.isTest.toString()}</td>
        <td>{detection.basestationId}</td>
        <td>{detection.detectorName}</td>
        <td>{detection.score}</td>
        <td>{detection.message}</td>
        <td>{detection.longitude}</td>
        <td>{detection.latitude}</td>
        <td>{moment(detection.createdAt).format()}</td>
        <td>{detection.readingIds[0]}</td>
      </tr>
    );
  }

  // Render readings or display loading screen
  renderDetections() {
    if(this.props.ready) {
      return (
        <table className="table table-hover">
          <thead>
            <tr>
              <th>Device ID</th>
              <th>Is test</th>
              <th>Basestation ID</th>
              <th>Detector Name</th>
              <th>Score</th>
              <th>Message</th>
              <th>Latitude</th>
              <th>Longitude</th>
              <th>Created at</th>
              <th>Reading IDs</th>
            </tr>
          </thead>
          <tbody>
            {this.props.detections.map(this.renderDetection)}
          </tbody>
        </table>
      );
    } else {
      return (
        <h1>Loading..</h1>
      )
    }
  }

  render() {
    return (
      <div className="container-fluid">
        <h1>Detections Page</h1>
        {this.renderDetections()}
        <hr />
        {this.renderDetectionGenerator()}
      </div>
    )
  }
}

export default createContainer( ({secret}) => {
  const detectionsHandle = Meteor.subscribe('catcher.secrets.detections', secret);
  const ready = detectionsHandle.ready();
  const detections = Catcher.Detections.find().fetch();

  return {
    ready: ready,
    detections: detections
  };
}, DetectionsPage);
